on:
  workflow_dispatch:
  schedule: 
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITH_EMAIL: ch1994@outlook.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
